fix:docker compose strategy

diff --git a/site-public/Dockerfile b/site-public/Dockerfile
--- a/site-public/Dockerfile
+++ b/site-public/Dockerfile
@@ -1,23 +1,56 @@
-# Use an official Node.js image as the base
-FROM node:20-alpine
+# syntax=docker.io/docker/dockerfile:1
 
-# Create and set the working directory
+FROM node:20-alpine AS base
+
+# Install dependencies only when needed
+FROM base AS deps
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-# Copy the necessary files to the container
-COPY package*.json ./
+# Install dependencies based on the preferred package manager
+COPY site-public/package.json site-public/yarn.lock* site-public/package-lock.json* site-public/pnpm-lock.yaml* site-public/.npmrc* ./
 
-# Install the dependencies
-RUN npm install
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# Copy the rest of the project to the container
-COPY . .
 
-# Build the Next.js app
-RUN npm run build
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY site-public/. .
 
-# Expose the port on which the app will run
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
+
+ENV NODE_ENV=production
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
 EXPOSE 3000
 
-# Define the command to start the app
-CMD ["npm", "start"]
+ENV PORT=3000
+
+# server.js is created by next build from the standalone output
+ENV HOSTNAME="0.0.0.0"
+CMD ["node", "server.js"]
